module.exports = {
    'GET /cardtable/list': './mock/cardtable/list.json',
    'GET /cardtable/map': './mock/cardtable/map.json',

    'GET /zhuangtai/table1': './mock/zhuangtai/table1.json',
    'GET /zhuangtai/table2': './mock/zhuangtai/table2.json',

    'GET /wuliuquanxian/wuliuguizhe': './mock/wuliuquanxian/wuliuguizhe.json',
    'GET /wuliuquanxian/xiangqing': './mock/wuliuquanxian/xiangqing.json',
    'GET /wuliuquanxian/pageInit': './mock/wuliuquanxian/pageInit.json',
    'GET /supplementCycleMaintain/supplementCycleMaintain': './mock/supplementCycleMaintain/supplementCycleMaintain.json',
    'GET /materialMaintain/materialMaintain': './mock/materialMaintain/materialMaintain.json',
    'GET /productStructure/productStructure': './mock/productStructure/productStructure.json',
    'GET /partBase/partBase': './mock/partBase/partBase.json',
    'GET /partBase/partBaseDropDown': './mock/partBase/partBaseDropDown.json',
    'GET /partBase/partType': './mock/partBase/partType.json',
    'GET /imgManage/imgManage': './mock/imgManage/imgManage.json',
    'GET /supplyReason/supplyReason': './mock/supplyReason/supplyReason.json',
    'GET /BillFinshedDeclare/BillFinshedDeclareDropDowns': './mock/BillFinshedDeclare/BillFinshedDeclareDropDowns.json',
    'GET /BillFinshedDeclare/orderNumSearch': './mock/BillFinshedDeclare/orderNumSearch.json',
    'GET /BillFinshedDeclare/fiveGold': './mock/BillFinshedDeclare/fiveGold.json',
    'GET /BillFinshedDeclare/plate': './mock/BillFinshedDeclare/plate.json',
    'GET /BillFinshedDeclare/orderNumSearchDialog1': './mock/BillFinshedDeclare/orderNumSearchDialog1.json',
    'GET /BillFinshedDeclare/orderNumSearchDialog2': './mock/BillFinshedDeclare/orderNumSearchDialog2.json',
    'GET /pathType/pathType': './mock/pathType/pathType.json',
    'GET /BillCustomDeclare/BillCustomDeclareDropDown': './mock/BillCustomDeclare/BillCustomDeclareDropDown.json',
    'GET /BillAuditFirst/BillAuditFirstDropDown': './mock/BillAuditFirst/BillAuditFirstDropDown.json',
    'GET /BillAuditFirst/customizationGrid': './mock/BillAuditFirst/customizationGrid.json',
    'GET /BillAuditFirst/standardGrid': './mock/BillAuditFirst/standardGrid.json',
    'GET /BillAuitRecheck/BillAuitRecheck': './mock/BillAuitRecheck/BillAuitRecheck.json',
    'GET /pbillOrderFollow/pbillOrderFollow': './mock/pbillOrderFollow/pbillOrderFollow.json',
    'GET /pbillOrderFollow/pbillOrderFollowDropdowns': './mock/pbillOrderFollow/pbillOrderFollowDropdowns.json',
    'GET /unusualWaring/unusualWaring': './mock/unusualWaring/unusualWaring.json'
};
